font_family      FiraCode
font_size 9.0

cursor #586e75
cursor_text_color #002b36

enable_audio_bell no

active_border_color #002b36
inactive_border_color #002b36
bell_border_color #ff5a00

url_color #0087bd

foreground #657b83
background #002b36

selection_foreground #002b36
selection_background #657b83

color0  #073642
color1  #dc322f
color2  #859900
color3  #b58900
color4  #268bd2
color5  #d33682
color6  #2aa198
color7  #073642
color8  #002b36
color9  #cb4b16
color10 #93a1a1
color11 #839496
color12 #657b83
color13 #6c71c4
color14 #586e75
color15 #002b36

# vim:fileencoding=utf-8:ft=conf:foldmethod=marker
