#!/bin/sh

# source global xinit files
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# force DPI value for DELL XPS 9360 QHD+
xrandr --dpi 277

# merge defaults, keymaps and keybindings
[ -f ~/.Xresources ] && xrdb -merge -I$HOME ~/.Xresources
[ -f ~/.Xmodmap ] && xmodmap ~/.Xmodmap
[ -f ~/.xbindkeysrc ] && xbindkeys

# set background
xsetroot -solid "#FDF6E3"

# Dell XPS 9360 QHD+ ICC profile from notebookcheck
# https://www.notebookcheck.net/Dell-XPS-13-9360-QHD-i7-7500U-Notebook-Review.181471.0.html
dispwin -d1 ~/.color/icc/RXN49_LQ133Z1_01.icm

libinput-gestures-setup start
