#!/bin/sh

# force DPI value
xrandr --dpi 227

# merge in defaults, keymaps and keybindings
[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources
[ -f ~/.Xmodmap ] && xmodmap ~/.Xmodmap
[ -f ~/.xbindkeysrc ] && xbindkeys

# source global xinit files
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# load ICC color profile
dispwin -display :0 ~/.color/icc/Color_LCD-02129CB1-7138-2EC6-188B-1630CBD51381.icc &

# Enable multiple monitors
xrandr-hdmi-toggle.sh

# set background
sh ~/.fehbg &
