gesture: swipe right 3 swaymsg -t command workspace  prev_on_output
gesture: swipe left  3 swaymsg -t command workspace  next_on_output
gesture: swipe up    3 swaymsg -t command fullscreen toggle
gesture: swipe down  3 swaymsg -t command floating   toggle
