swipe:
  3:
    left:
      sendkey: "LEFTALT+RIGHT" # history back
    right:
      sendkey: "LEFTALT+LEFT" # history forward
    up:
      sendkey: "LEFTCTRL+T" # open new tab
    down:
      sendkey: "LEFTCTRL+W" # close tab
  4:
    up:
      sendkey: 'LEFTALT+F' # fullscreen
      keypress:
        LEFTMETA:
          command: 'VOLUMEUP' # not working
        LEFTMETA+LEFTCTRL:
          command: 'BRIGHTNESSUP' # not working
    down:
      sendkey: "LEFTALT+F" # fullscreen
      keypress:
        LEFTMETA:
          command: 'VOLUMEDOWN' # not working
        LEFTMETA+LEFTCTRL:
          command: 'BRIGHTNESSDOWN' # not working
plugin:
  inputs:
    libinput_command_input:
      show-keycodes: true
