# Video
F1 set video-aspect 4:3
F2 set video-aspect 5:3
F3 set video-aspect 16:9
F4 set video-aspect 1.85:1
F5 set video-aspect 2.39:1
F6 set video-aspect -1

# Audio
TAB cycle_values audio-device auto alsa/hdmi
H set audio-device alsa/default:CARD=Headset # crashes when device is unavailable

# Subtitles
Z sub-step -1                         # immediately display next subtitle
X sub-step +1                         #                     previous

# vim:ft=conf:
