# video
fs=yes
ontop=yes

# audio
alang=jp,jpn,el,ell,gr,gre,en,eng,
audio-device=alsa

# subtitles
slang=el,ell,gr,gre,en,eng
sub-auto=fuzzy
sub-file-paths=sub:Subtitles:subtitles

# profiles
profile=opengl-hq

[tv]
x11-name=TV
audio-device=alsa/hdmi

[audio]
video=no
