# video
fs=yes
ontop=yes
hwdec=auto

# audio
alang=jp,jpn,el,ell,gr,gre,en,eng,

# subtitles
slang=el,ell,gr,gre,en,eng
sub-auto=fuzzy
sub-file-paths=sub:Subtitles:subtitles

# profiles
profile=opengl-hq

[audio]
video=no

[hdmi]
x11-name=TV
#audio-device=alsa/hdmi
script=~/.config/mpv/tv/xrandr.lua

[sop]
profile=hdmi
profile=low-latency
no-ytdl

[tv]
profile=hdmi
profile=opengl-hq

# vim:set ft=cfg:
