# video
#vo=opengl-hq,
fs=yes
ontop=yes

# audio
alang=jp,jpn,el,gr,gre,en,eng,

# subtitles
slang=el,gr,gre,en,eng
sub-auto=fuzzy
sub-paths=sub:Subtitles:subtitles
# compatibility: fall back to Windows-1253 code page (Greek)
sub-codepage=utf8:cp1253

# osd
osd-level=1

# profiles
[tv]
x11-name=TV
audio-device='alsa/hdmi:CARD=PCH,DEV=0'
msg-level=all=error
