background #fdf6e3
foreground #839496
active_border_color #fdf6e3
inactive_border_color #fdf6e3
cursor #93a1a1
cursor_text_color #586e75
selection_foreground #fdf6e3
selection_background #657b83
url_color #0087bd

color0  #262626
color1  #d70000
color2  #5f8700
color3  #af8700
color4  #0087ff
color5  #af005f
color6  #00afaf
color7  #d7d7af
color8  #1c1c1c
color9  #d75f00
color10 #4e4e4e
color11 #585858
color12 #808080
color13 #5f5faf
color14 #8a8a8a
color15 #ffffd7

# vim:fileencoding=utf-8:ft=conf:foldmethod=marker
